name: Autograding Tests
on: ["push", "repository_dispatch"]
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    services:
          postgres:
            image: postgres:13  # Use PostgreSQL version 13
            env:
              POSTGRES_DB: your_database_name
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: your_strong_password
            ports:
              - 5432:5432  # Map PostgreSQL port to the host
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psycopg2
    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h localhost -p 5432 -U postgres; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 5
        done
    - name: Check SQL Scripts
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_NAME: TEST_DB
        DB_USER: postgres
        DB_PASS: secured123
      id: check-sql-scripts
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Check if SQL Script Works
        command: "python tests/test.py"
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CHECK-SQL-SCRIPTS_RESULTS: "${{steps.check-sql-scripts.outputs.result}}"
      with:
        runners: check-sql-scripts
