name: Testing SQL Scripts

on:
  push:
    branches: [main] # Trigger on pushes to the main branch

jobs:
    grade:
        runs-on: ubuntu-latest
    
        services:
          postgres:
            image: postgres:13  # Use PostgreSQL version 13
            env:
              POSTGRES_DB: your_database_name
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: your_strong_password
            ports:
              - 5432:5432  # Map PostgreSQL port to the host
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
    
          - name: Install Python dependencies
            run: |
              python -m pip install --upgrade pip
              pip install psycopg2
    
          - name: Wait for PostgreSQL to be ready
            run: |
              until pg_isready -h localhost -p 5432 -U postgres; do
                echo "Waiting for PostgreSQL to be ready..."
                sleep 5
              done
    
          - name: Run grading script
            env:
              DB_HOST: localhost
              DB_PORT: 5432
              DB_NAME: your_database_name
              DB_USER: postgres
              DB_PASS: your_strong_password
            run: |
              python tests/test.py
    
          - name: Stop PostgreSQL service
            run: |
              docker stop $(docker ps -q --filter ancestor=postgres:13)
              docker rm $(docker ps -aq --filter ancestor=postgres:13)