name: Testing SQL Scripts

on:
  push:
    branches: [main] # Trigger on pushes to the main branch

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run MySQL container
        run: |
          docker build -t my-sql-container .
          docker run -d -p 3306:3306 --name my-sql-container my-sql-container