name: Autograding Tests
on: ["push", "repository_dispatch"]
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    services:
      mariadb:
        image: mariadb:10.5  # Use MariaDB version 10.5
        env:
          MYSQL_DATABASE: TEST_DB
          MYSQL_USER: root
          MYSQL_PASSWORD: secured123
          MYSQL_ROOT_PASSWORD: secured123
        ports:
          - 3306:3306  # Map MariaDB port to the host
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mysql-connector-python
    - name: Wait for MariaDB to be ready
      run: |
        until mysqladmin ping -h "127.0.0.1" --silent; do
          echo "Waiting for MariaDB to be ready..."
          sleep 5
        done
    - name: Check SQL Scripts
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_NAME: TEST_DB
        DB_USER: root
        DB_PASS: secured123
      id: check-sql-scripts
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Check if SQL Script Works
        command: "python tests/test.py"
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CHECK-SQL-SCRIPTS_RESULTS: "${{steps.check-sql-scripts.outputs.result}}"
      with:
        runners: check-sql-scripts
