name: Testing SQL Scripts

on:
  push:
    branches: [main] # Trigger on pushes to the main branch

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run MySQL container
        run: |
          docker build -t my-sql-container .
          docker run -d -p 3306:3306 --name my-sql-container my-sql-container

      - name: Install Python Dependencies
        run: |
            pip install psycopg2

      - name: Run grading script
        run: |
            python tests/test.py

      - name: Stop and remove MySQL container
        run: |
            docker stop my-sql-container
            docker rm my-sql-container